#ifndef _REG_H
#define _REG_H

enum
{
  E_SHREDDER_ON_OFF_1 = 0,
  E_SHREDDER_ON_OFF_2,
  E_WEIGHT_1,
  E_WEIGHT_2,
  E_BLEND_SYSTEM_ON_OFF,
  E_ACTUATOR_H_IN_OUT,
  E_ACTUATOR_H_EN,
  E_ACTUATOR_V_UP,
  E_ACTUATOR_V_DOWN,
  E_ACTUATOR_V_FLUSH,
  E_ACTUATOR_V_EN,
  E_ACTUATOR_V_SPEED_1,
  E_ACTUATOR_V_SPEED_2,
  E_ACTUATOR_V_TIME_2,
  E_ACTUATOR_V_SPEED_3,
  E_ACTUATOR_V_SPEED_4,
  E_ACTUATOR_V_TIME_4,
  E_ACTUATOR_V_SPEED_5,
  E_ACTUATOR_V_SPEED_6,
  E_ACTUATOR_V_TIME_6,
  E_ACTUATOR_V_SPEED_7,
  E_ACTUATOR_V_SPEED_8,
  E_ACTUATOR_V_TIME_8,
  E_ACTUATOR_V_SPEED_9,
  E_MIXER_ON_OFF,
  E_PUMP_ON_OFF,
  E_FLUSH_TIME,
  E_DISPENSER_DRY_ON_OFF,
  E_DISPENSER_DRY_COUNT,
  E_NU_1, // NOT USE
  E_DISPENSER_LIQ_ON_OFF,
  E_DISPENSER_LIQ_TIME,
  E_NU_2, // NOT USE
  E_SERVO_PWM,
  E_ACTUATOR_V_DELAY_1,
  E_ACTUATOR_V_DELAY_2,
  E_ACTUATOR_V_DELAY_3,
  E_INIT_SYSTEM_ON_OFF,
  E_MIXER_DELAY_START,
  E_EMERGENCY_STOP,
  E_HEARTBIT,
  E_HEARTBIT_START_STOP,
  E_HEARTBIT_FREQ,
  E_VERSION = 255
}

#endif // _REG_H
